{% set name = "nf1" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nf1-{{ version }}.tar.gz
  sha256: 09cfd6d2b219d62e5be12ba037c06670344cd1477b8cb4826726760b8528bb4b

build:
  entry_points:
    - NF1_evaluate = scripts.NF1_evaluate:execute
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools <58
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - scipy
    - pandas

test:
  imports:
    - nf1
    - scripts
  commands:
    - pip check
    - NF1_evaluate --help
  requires:
    - pip

about:
  home: https://github.com/GiulioRossetti/f1-communities
  summary: 'NF1: Normalized F1 score for community evaluation against ground truth'
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
